#!/bin/bash

#PBS -q normal
#PBS -P 11001079
#PBS -l select=1:ncpus=1:mem=8G
#PBS -l walltime=20:00:00
#PBS -N Strelka_Head
#PBS -o /home/users/industry/uchicago/tsummer2/outputfiles/Strelka_Head.o
#PBS -e /home/users/industry/uchicago/tsummer2/errorfiles/Strelka_Head.e

echo "Started head task"

module load anaconda/3
source activate parsl_py36

echo "Env setup"

cd /home/users/industry/uchicago/tsummer2/testParsl/nscc/strelkaCPU

echo "Running task..."
pwd
ls

python strelkaCPU.py