#!/bin/bash

#PBS -q normal
#PBS -P 11001079
#PBS -l select=1:ncpus=1:mem=100M
#PBS -l walltime=00:10:00
#PBS -N Strelka_Head
#PBS -o /home/users/industry/uchicago/tsummer2/outputfiles/Sub_Head.o
#PBS -e /home/users/industry/uchicago/tsummer2/errorfiles/Sub_Head.e

echo "Started head task"

module load anaconda/3
source activate parsl_py36

echo "Env setup"

cd /home/users/industry/uchicago/tsummer2/testParsl/nscc/submitTest

echo "Running task..."
pwd
ls

qsub node.pbs